package Utils;
import java.util.List;
import java.util.ArrayList;
public class QueQuan {
    private static List<String> queQuan = new ArrayList<>();
    public static List<String> getQueQuan(){
        queQuan.add("Hà Nội");
        queQuan.add("Vĩnh Phúc");
        queQuan.add("Bắc Ninh");
        queQuan.add("Quảng Ninh");
        queQuan.add("Hải Dương");
        queQuan.add("Hải Phòng");
        queQuan.add("Thái Bình");
        queQuan.add("Hà Nam");
        queQuan.add("Nam Định");
        queQuan.add("Ninh Bình");
        queQuan.add("Hà Giang");
        queQuan.add("Cao Bằng");
        queQuan.add("Bắc Kạn");
        queQuan.add("Tuyên Quang");
        queQuan.add("Lào Cai");
        queQuan.add("Yên Bái");
        queQuan.add("Thái Nguyên");
        queQuan.add("Lạng Sơn");
        queQuan.add("Bắc Giang");
        queQuan.add("Phú Thọ");
        queQuan.add("Điện Biên");
        queQuan.add("Lai Châu");
        queQuan.add("Sơn La");
        queQuan.add("Hoà Bình");
        queQuan.add("Thanh Hoá");
        queQuan.add("Nghệ An");
        queQuan.add("Hà Tĩnh");
        queQuan.add("Quảng Bình");
        queQuan.add("Quảng Trị");
        queQuan.add("Thừa Thiên Huế");
        queQuan.add("Đà Nẵng");
        queQuan.add("Quảng Nam");
        queQuan.add("Quảng Ngãi");
        queQuan.add("Bình Định");
        queQuan.add("Phú Yên");
        queQuan.add("Khánh Hoà");
        queQuan.add("Ninh Thuận");
        queQuan.add("Bình Thuận");
        queQuan.add("Kon Tum");
        queQuan.add("Gia Lai");
        queQuan.add("Đắk Lắk");
        queQuan.add("Đắk Nông");
        queQuan.add("Lâm Đồng");
        queQuan.add("Bình Phước");
        queQuan.add("Tây Ninh");
        queQuan.add("Bình Dương");
        queQuan.add("Đồng Nai");
        queQuan.add("Bà Rịa - Vũng Tàu");
        queQuan.add("TP.Hồ Chí Minh");
        queQuan.add("Long An");
        queQuan.add("Tiền Giang");
        queQuan.add("Bến Tre");
        queQuan.add("Trà Vinh");
        queQuan.add("Vĩnh Long");
        queQuan.add("Đồng Tháp");
        queQuan.add("An Giang");
        queQuan.add("Kiên Giang");
        queQuan.add("Cần Thơ");
        queQuan.add("Hậu Giang");
        queQuan.add("Sóc Trăng");
        queQuan.add("Bạc Liêu");
        queQuan.add("Cà Mau");
        
        
        return queQuan;
    }
}
